apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: users-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: default
  source:
    path: services/users
    repoURL: https://github.com/Maverickme222222/deploy
    targetRevision: HEAD