apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-appbundle-app-dev
  namespace: argocd
spec:
  destination:
    namespace: default
    name: in-cluster
  project: appbundle-project-dev
  source:
    path: services/
    repoURL: https://github.com/Maverickme222222/deploy
    targetRevision: HEAD