apiVersion: apps/v1
kind: Deployment
metadata:
  name: emails
  labels:
    app: emails
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emails
      version: v1
  template:
    metadata:
      labels:
        app: emails
        version: v1
    spec:
      containers:
        - name: emails
          image: registry.hub.docker.com/maverickme22/emails:v0.0.1
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 9090
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9090"]
            initialDelaySeconds: 10
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9090"]
            initialDelaySeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: emails
  labels:
    app: emails
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      name: grpc-emails
  selector:
    app: emails
    version: v1
