apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
      version: v1
  template:
    metadata:
      labels:
        app: users
        version: v1
    spec:
      containers:
        - name: users
          image: registry.hub.docker.com/maverickme22/users:v0.0.1
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 9090
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9090"]
            initialDelaySeconds: 10
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9090"]
            initialDelaySeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: users
  labels:
    app: users
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      name: grpc-users
  selector:
    app: users
    version: v1
