apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: users-rollout
spec:
  replicas: 2
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: users
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 10s}
        - setWeight: 40
        - setWeight: 60
        - setWeight: 80
        - setWeight: 100