apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-api-app-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: appbundle-project-dev
  source:
    path: kustomized_helm/overlays/dev
    repoURL: https://github.com/Maverickme222222/api
    targetRevision: HEAD
    plugin:
      name: kustomized-helm